added 'addr' command which append the latest context and project tags…
todotxt/todo.txt-cli pull request #182
Opened 2016-06-21 04:56 UTC by mhalano

added 'addr' command which append the latest context and project tags to a new item. I created using this add-on code:
https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#addr--add-task-with-the-projects-and-contexts-of-the-last-added-task

2020-09-20 01:00 UTC, mhalano commented
@karbassi Could you merge this if all changes are ok?

2020-09-20 10:26 UTC, inkarkat requested changes
There are still some loose ends here. Most importantly, you did not add any new tests yet that exercise the new command.

Also, while I see how this could indeed be useful, I doubt that the majority of todo.txt users would benefit greatly from this (because I haven't seen an existing add-on for this, and nobody has yet asked for this functionality) - but this is just my own opinion.

Things get added to the core todo.sh script because either these are hard or impossible to do with add-ons, or because an add-on has seen such widespread use that it makes sense to put this right into core.

So, the easy way out for you would be to turn this into an add-on (which should be trivial), and maybe share this with the community. The other alternative (provided that @karbassi is a bit more positive about the inclusion) would be to address the issues and add tests.

2020-09-20 10:26 UTC, inkarkat commented on todo.sh
> +		      Append the tags of the most recently added item
"Tags" is not part of the todo.txt vocabulary. These are always referred to as "projects and contexts".

2020-09-20 10:26 UTC, inkarkat commented on todo.sh
> +	"$TODO_FULL_SH" command add "$1"
Yes, `_addto` should be used. Recursively invoking the script is not needed, and bad style.

2020-09-20 10:26 UTC, inkarkat commented on todo.sh
> +	REGEX='[@|+][A-Za-z0-9]*'
That is not the correct pattern to extract all projects and contexts. In fact, this now is configurable via `TODOTXT_SIGIL_VALID_PATTERN`. The `listWordsWithSigil()` function can extract these for you.

2020-09-20 10:26 UTC, inkarkat commented on todo.sh
> +	# FIXME: Find a better way to append content
Again, don't do a recursive call. Either duplicate the `sed` call found in the `append` implementation, or (better) extract a new function and use that for both.

2020-09-20 10:26 UTC, inkarkat commented on todo.sh
> +	# set priority
Please remove commented-out code.

2021-08-04 17:28 UTC, karbassi commented
Since @mhalano created an addon for this, let's keep it as an addon to limit updates to the core.

I'm open to discussion though, if anyone feels strongly about this.

2021-08-04 17:28 UTC, closed without merging