Read the task's name and uses as default
todotxt/todo.txt-cli pull request #249
Opened 2018-03-23 19:45 UTC by guifeliper

Read the task's name and uses as default, so the user can read the previous task's name.
This commit is an answer to the issue #245.

Fixes #245 

**Before submitting a pull request,** please make sure the following is done:

- [x] Fork [the repository](https://github.com/todotxt/todo.txt-cli) and create your branch from `master`.
- [x] If you've added code that should be tested, add tests!
- [x] Ensure the test suite passes.
- [x] Format your code with [ShellCheck](https://www.shellcheck.net/).
- [x] Include a human-readable description of what the pull request is trying to accomplish.
- [x] Steps for the reviewer(s) on how they can manually QA the changes.
- [x] Have a `fixes #245` reference to the issue that this pull request fixes.

2018-03-23 21:16 UTC, inkarkat requested changes
At least in my Bash 4.3.48(1)-release, the variable (`input`) needs to come last:

    -bash: read: `-r': not a valid identifier

2018-03-24 18:17 UTC, guifeliper commented
@inkarkat you seem to be right, my local version is 
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

The version of GNU bash, version 4.4.5(1)-release has the same behaviour you mentioned above. 
I suggest we use 
`read  -r -i $todo -e input`

2018-03-26 16:18 UTC, karbassi commented
@inkarkat thoughts on this merge? Is it good to go with @guifeliper's updates?

2018-03-26 16:24 UTC, inkarkat approved these changes

2018-03-26 18:23 UTC, merged